accounts:
  prod-main-web: "111111111111"
  prod-main-api: "222222222222"
  prod-data-analytics: "333333333333"
  prod-logging: "444444444444"
  dev-infra: "555555555555"
  dev-app-alpha: "666666666666"
  dev-sandbox-user1: "777777777777"
  staging-main: "888888888888"
  qa-performance: "999999999999"
  shared-network: "012345678901"
  security-audit: "109876543210"

common_regions:
  - "us-east-1"
  - "us-east-2"
  - "us-west-1"
  - "us-west-2"
  - "eu-west-1"
  - "eu-west-2"
  - "eu-central-1"
  - "ap-southeast-1"
  - "ap-southeast-2"
  - "ap-northeast-1"

roles:
  Admin: "OrganizationAccountAccessRole"
  PowerUser: "PowerUserRole"
  ReadOnly: "ViewOnlyAccess"
  Developer: "DeveloperAccessRole"
  Support: "SupportRole"
  AppDeployer: "MyWebAppDeploymentRole"
  DatabaseAdmin: "RDSFullAccessRole"
  LambdaExec: "BasicLambdaExecutionRole"
